spring:
  application:
    name: cloud-gateway
  cloud:    gateway:      routes:      - id: order-service
        uri: lb://order-mgmt-service
        predicates:          - Path=/orders/**
#        filters:#          - name: CircuitBreaker
#            args:#              name: order-service
#              fallbackuri: forward:/orderfallback
      - id: payment-service
        uri: lb://payment-mgmt-service
        predicates:
          - Path=/payments/**
#        filters:
#          - name: CircuitBreaker
#            args:
#              name: payment-service
#              fallbackuri: forward:/paymentfallback
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
