spring:
  application:
    name: order-mgmt-service
server:  port: 8011
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:    hostname: localhost